/********************************************************************************
** Form generated from reading UI file 'qtapplication.ui'
**
** Created by: Qt User Interface Compiler version 5.4.0
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_QTAPPLICATION_H
#define UI_QTAPPLICATION_H

#include <QtCore/QLocale>
#include <QtCore/QVariant>
#include <QtWidgets/QAction>
#include <QtWidgets/QApplication>
#include <QtWidgets/QButtonGroup>
#include <QtWidgets/QCheckBox>
#include <QtWidgets/QComboBox>
#include <QtWidgets/QDial>
#include <QtWidgets/QDockWidget>
#include <QtWidgets/QDoubleSpinBox>
#include <QtWidgets/QFrame>
#include <QtWidgets/QGroupBox>
#include <QtWidgets/QHBoxLayout>
#include <QtWidgets/QHeaderView>
#include <QtWidgets/QLabel>
#include <QtWidgets/QMainWindow>
#include <QtWidgets/QMenu>
#include <QtWidgets/QMenuBar>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QScrollArea>
#include <QtWidgets/QScrollBar>
#include <QtWidgets/QSplitter>
#include <QtWidgets/QTabWidget>
#include <QtWidgets/QToolBar>
#include <QtWidgets/QVBoxLayout>
#include <QtWidgets/QWidget>

QT_BEGIN_NAMESPACE

class Ui_QtApplicationClass
{
public:
    QAction *actionOpen;
    QAction *action_Save;
    QAction *action_Open;
    QAction *actionSave_As;
    QAction *action_Quit;
    QAction *action_Play;
    QAction *action_Reset;
    QAction *actionSave_as;
    QAction *action_About;
    QAction *actionSave;
    QAction *action_About_2;
    QAction *action_ToolBar;
    QAction *actionMaximum;
    QAction *actionMinimum;
    QAction *actionFull_Screen;
    QWidget *centralWidget;
    QVBoxLayout *verticalLayout;
    QWidget *widget_2;
    QVBoxLayout *verticalLayout_4;
    QVBoxLayout *verticalLayout_3;
    QTabWidget *tabWidget;
    QWidget *tab;
    QHBoxLayout *horizontalLayout;
    QGroupBox *groupBox_10;
    QScrollBar *horizontalScrollBar_17;
    QScrollBar *horizontalScrollBar_18;
    QScrollBar *horizontalScrollBar_19;
    QScrollBar *horizontalScrollBar_20;
    QLabel *label_62;
    QLabel *label_63;
    QLabel *label_64;
    QLabel *label_65;
    QSplitter *splitter_5;
    QLabel *label_66;
    QLabel *label_67;
    QLabel *label_68;
    QLabel *label_69;
    QPushButton *pushButton_3;
    QGroupBox *groupBox_11;
    QScrollBar *horizontalScrollBar_21;
    QScrollBar *horizontalScrollBar_22;
    QScrollBar *horizontalScrollBar_23;
    QScrollBar *horizontalScrollBar_24;
    QLabel *label_70;
    QLabel *label_71;
    QLabel *label_72;
    QLabel *label_73;
    QSplitter *splitter_6;
    QLabel *label_74;
    QLabel *label_75;
    QLabel *label_76;
    QLabel *label_77;
    QPushButton *pushButton_4;
    QWidget *tab_2;
    QHBoxLayout *horizontalLayout_2;
    QGroupBox *groupBox_8;
    QScrollBar *horizontalScrollBar_9;
    QScrollBar *horizontalScrollBar_10;
    QScrollBar *horizontalScrollBar_11;
    QScrollBar *horizontalScrollBar_12;
    QLabel *label_46;
    QLabel *label_47;
    QLabel *label_48;
    QLabel *label_49;
    QSplitter *splitter_3;
    QLabel *label_50;
    QLabel *label_51;
    QLabel *label_52;
    QLabel *label_53;
    QPushButton *pushButton_5;
    QGroupBox *groupBox_9;
    QScrollBar *horizontalScrollBar_13;
    QScrollBar *horizontalScrollBar_14;
    QScrollBar *horizontalScrollBar_15;
    QScrollBar *horizontalScrollBar_16;
    QLabel *label_54;
    QLabel *label_55;
    QLabel *label_56;
    QLabel *label_57;
    QSplitter *splitter_4;
    QLabel *label_58;
    QLabel *label_59;
    QLabel *label_60;
    QLabel *label_61;
    QPushButton *pushButton_6;
    QWidget *tab_3;
    QHBoxLayout *horizontalLayout_3;
    QGroupBox *groupBox_6;
    QScrollBar *horizontalScrollBar;
    QScrollBar *horizontalScrollBar_2;
    QScrollBar *horizontalScrollBar_3;
    QScrollBar *horizontalScrollBar_4;
    QLabel *label_26;
    QLabel *label_27;
    QLabel *label_36;
    QLabel *label_37;
    QSplitter *splitter;
    QLabel *label_22;
    QLabel *label_23;
    QLabel *label_24;
    QLabel *label_25;
    QPushButton *pushButton_7;
    QGroupBox *groupBox_7;
    QLabel *label_87;
    QPushButton *pushButton;
    QCheckBox *checkBox;
    QCheckBox *checkBox_2;
    QMenuBar *menuBar;
    QMenu *menu_File;
    QMenu *menu_History;
    QMenu *menu_View;
    QMenu *menu_Window;
    QMenu *menu_Example;
    QMenu *menu_Help;
    QToolBar *mainToolBar;
    QDockWidget *Properties;
    QWidget *dockWidgetContents;
    QLabel *label;
    QFrame *line;
    QDial *dial;
    QDoubleSpinBox *doubleSpinBox;
    QFrame *line_2;
    QDial *dial_2;
    QLabel *label_2;
    QDoubleSpinBox *doubleSpinBox_2;
    QFrame *line_3;
    QLabel *label_3;
    QDial *dial_3;
    QDoubleSpinBox *doubleSpinBox_3;
    QDoubleSpinBox *doubleSpinBox_4;
    QLabel *label_4;
    QFrame *line_4;
    QDial *dial_4;
    QFrame *line_5;
    QLabel *label_5;
    QDial *dial_5;
    QDoubleSpinBox *doubleSpinBox_5;
    QFrame *line_6;
    QDoubleSpinBox *doubleSpinBox_6;
    QLabel *label_6;
    QDial *dial_6;
    QFrame *line_7;
    QLabel *label_7;
    QDoubleSpinBox *doubleSpinBox_7;
    QDial *dial_7;
    QFrame *line_8;
    QDoubleSpinBox *doubleSpinBox_8;
    QLabel *label_8;
    QDial *dial_8;
    QDoubleSpinBox *doubleSpinBox_14;
    QLabel *label_14;
    QDial *dial_14;
    QFrame *line_14;
    QFrame *line_15;
    QDial *dial_15;
    QDoubleSpinBox *doubleSpinBox_15;
    QLabel *label_15;
    QFrame *line_16;
    QDial *dial_16;
    QDoubleSpinBox *doubleSpinBox_16;
    QLabel *label_16;
    QDoubleSpinBox *doubleSpinBox_17;
    QLabel *label_17;
    QFrame *line_17;
    QDial *dial_17;
    QFrame *line_18;
    QLabel *label_18;
    QDoubleSpinBox *doubleSpinBox_18;
    QDial *dial_18;
    QFrame *line_19;
    QDoubleSpinBox *doubleSpinBox_19;
    QDial *dial_19;
    QLabel *label_19;
    QDockWidget *Blend;
    QWidget *dockWidgetContents_2;
    QLabel *label_20;
    QComboBox *comboBox;
    QPushButton *btn_normal;
    QLabel *label_21;
    QPushButton *pushButton_2;
    QComboBox *comboBox_2;
    QDockWidget *dockWidget;
    QWidget *dockWidgetContents_3;
    QWidget *widget;
    QLabel *label_86;
    QPushButton *choose_texture;
    QDockWidget *dockWidget_2;
    QWidget *dockWidgetContents_5;
    QVBoxLayout *verticalLayout_2;
    QFrame *frame;
    QScrollArea *scrollArea_2;
    QWidget *scrollAreaWidgetContents_2;
    QLabel *label_31;
    QComboBox *comboBox_4;
    QFrame *frame_01;
    QLabel *label_30;
    QDial *dial_rotatevar;
    QDial *dial_minr;
    QLabel *label_32;
    QDial *dial_maxr;
    QDoubleSpinBox *doubleSpinBox_maxr;
    QDoubleSpinBox *doubleSpinBox_minr;
    QFrame *line_27;
    QLabel *label_33;
    QDoubleSpinBox *doubleSpinBox_maxrv;
    QDoubleSpinBox *doubleSpinBox_rotate;
    QLabel *label_34;
    QDoubleSpinBox *doubleSpinBox_rotatevar;
    QDial *dial_maxrv;
    QDial *dial_rotate;
    QLabel *label_35;
    QFrame *line_28;
    QFrame *line_29;
    QFrame *line_30;
    QFrame *line_31;
    QFrame *frame_2;
    QLabel *label_78;
    QDial *dial_radial;
    QDial *dial_gravityx;
    QLabel *label_79;
    QDial *dial_speed;
    QDoubleSpinBox *doubleSpinBox_speed;
    QDoubleSpinBox *doubleSpinBox_gravityx;
    QFrame *line_32;
    QLabel *label_80;
    QDoubleSpinBox *doubleSpinBox_speedVar;
    QDoubleSpinBox *doubleSpinBox_gravityy;
    QLabel *label_81;
    QDoubleSpinBox *doubleSpinBox_radial;
    QDial *dial_speedVar;
    QDial *dial_gravityy;
    QLabel *label_82;
    QFrame *line_33;
    QFrame *line_34;
    QFrame *line_35;
    QFrame *line_36;
    QFrame *line_39;
    QDoubleSpinBox *doubleSpinBox_tangential;
    QLabel *label_85;
    QDial *dial_radialvar;
    QDoubleSpinBox *doubleSpinBox_radialvar;
    QDial *dial_tangential;
    QLabel *label_84;
    QDial *dial_tangvar;
    QLabel *label_83;
    QFrame *line_37;
    QFrame *line_38;
    QDoubleSpinBox *doubleSpinBox_tangvar;
    QGroupBox *groupBox;
    QFrame *line_25;
    QDoubleSpinBox *doubleSpinBox_x;
    QLabel *label_28;
    QDial *dial_x;
    QFrame *line_26;
    QLabel *label_29;
    QDoubleSpinBox *doubleSpinBox_y;
    QDial *dial_y;

    void setupUi(QMainWindow *QtApplicationClass)
    {
        if (QtApplicationClass->objectName().isEmpty())
            QtApplicationClass->setObjectName(QStringLiteral("QtApplicationClass"));
        QtApplicationClass->setWindowModality(Qt::ApplicationModal);
        QtApplicationClass->setEnabled(true);
        QtApplicationClass->resize(1000, 708);
        QtApplicationClass->setLayoutDirection(Qt::LeftToRight);
        QtApplicationClass->setLocale(QLocale(QLocale::Chinese, QLocale::China));
        QtApplicationClass->setToolButtonStyle(Qt::ToolButtonIconOnly);
        QtApplicationClass->setAnimated(true);
        QtApplicationClass->setDocumentMode(false);
        QtApplicationClass->setDockNestingEnabled(false);
        QtApplicationClass->setDockOptions(QMainWindow::AllowTabbedDocks|QMainWindow::AnimatedDocks|QMainWindow::VerticalTabs);
        actionOpen = new QAction(QtApplicationClass);
        actionOpen->setObjectName(QStringLiteral("actionOpen"));
        actionOpen->setCheckable(false);
        QIcon icon;
        icon.addFile(QStringLiteral(":/QtApplication/Resources/icon/2.png"), QSize(), QIcon::Normal, QIcon::Off);
        actionOpen->setIcon(icon);
        action_Save = new QAction(QtApplicationClass);
        action_Save->setObjectName(QStringLiteral("action_Save"));
        QIcon icon1;
        icon1.addFile(QStringLiteral(":/QtApplication/Resources/icon/save1.png"), QSize(), QIcon::Normal, QIcon::Off);
        action_Save->setIcon(icon1);
        action_Open = new QAction(QtApplicationClass);
        action_Open->setObjectName(QStringLiteral("action_Open"));
        action_Open->setCheckable(false);
        action_Open->setIcon(icon);
        actionSave_As = new QAction(QtApplicationClass);
        actionSave_As->setObjectName(QStringLiteral("actionSave_As"));
        QIcon icon2;
        icon2.addFile(QStringLiteral(":/QtApplication/Resources/icon/save as -1.png"), QSize(), QIcon::Normal, QIcon::Off);
        actionSave_As->setIcon(icon2);
        action_Quit = new QAction(QtApplicationClass);
        action_Quit->setObjectName(QStringLiteral("action_Quit"));
        action_Play = new QAction(QtApplicationClass);
        action_Play->setObjectName(QStringLiteral("action_Play"));
        QIcon icon3;
        icon3.addFile(QStringLiteral(":/QtApplication/Resources/icon/play 1.png"), QSize(), QIcon::Normal, QIcon::Off);
        action_Play->setIcon(icon3);
        action_Reset = new QAction(QtApplicationClass);
        action_Reset->setObjectName(QStringLiteral("action_Reset"));
        QIcon icon4;
        icon4.addFile(QStringLiteral(":/QtApplication/Resources/icon/save as 1.png"), QSize(), QIcon::Normal, QIcon::Off);
        action_Reset->setIcon(icon4);
        actionSave_as = new QAction(QtApplicationClass);
        actionSave_as->setObjectName(QStringLiteral("actionSave_as"));
        actionSave_as->setIcon(icon2);
        action_About = new QAction(QtApplicationClass);
        action_About->setObjectName(QStringLiteral("action_About"));
        QIcon icon5;
        icon5.addFile(QStringLiteral(":/QtApplication/Resources/icon/i-1.png"), QSize(), QIcon::Normal, QIcon::Off);
        action_About->setIcon(icon5);
        actionSave = new QAction(QtApplicationClass);
        actionSave->setObjectName(QStringLiteral("actionSave"));
        actionSave->setIcon(icon1);
        action_About_2 = new QAction(QtApplicationClass);
        action_About_2->setObjectName(QStringLiteral("action_About_2"));
        action_About_2->setIcon(icon5);
        action_ToolBar = new QAction(QtApplicationClass);
        action_ToolBar->setObjectName(QStringLiteral("action_ToolBar"));
        action_ToolBar->setCheckable(true);
        action_ToolBar->setChecked(true);
        actionMaximum = new QAction(QtApplicationClass);
        actionMaximum->setObjectName(QStringLiteral("actionMaximum"));
        actionMinimum = new QAction(QtApplicationClass);
        actionMinimum->setObjectName(QStringLiteral("actionMinimum"));
        actionFull_Screen = new QAction(QtApplicationClass);
        actionFull_Screen->setObjectName(QStringLiteral("actionFull_Screen"));
        centralWidget = new QWidget(QtApplicationClass);
        centralWidget->setObjectName(QStringLiteral("centralWidget"));
        verticalLayout = new QVBoxLayout(centralWidget);
        verticalLayout->setSpacing(6);
        verticalLayout->setContentsMargins(11, 11, 11, 11);
        verticalLayout->setObjectName(QStringLiteral("verticalLayout"));
        widget_2 = new QWidget(centralWidget);
        widget_2->setObjectName(QStringLiteral("widget_2"));
        verticalLayout_4 = new QVBoxLayout(widget_2);
        verticalLayout_4->setSpacing(6);
        verticalLayout_4->setContentsMargins(11, 11, 11, 11);
        verticalLayout_4->setObjectName(QStringLiteral("verticalLayout_4"));
        verticalLayout_3 = new QVBoxLayout();
        verticalLayout_3->setSpacing(6);
        verticalLayout_3->setObjectName(QStringLiteral("verticalLayout_3"));

        verticalLayout_4->addLayout(verticalLayout_3);


        verticalLayout->addWidget(widget_2);

        tabWidget = new QTabWidget(centralWidget);
        tabWidget->setObjectName(QStringLiteral("tabWidget"));
        tabWidget->setMinimumSize(QSize(460, 150));
        tabWidget->setMaximumSize(QSize(16777215, 150));
        tab = new QWidget();
        tab->setObjectName(QStringLiteral("tab"));
        horizontalLayout = new QHBoxLayout(tab);
        horizontalLayout->setSpacing(6);
        horizontalLayout->setContentsMargins(11, 11, 11, 11);
        horizontalLayout->setObjectName(QStringLiteral("horizontalLayout"));
        groupBox_10 = new QGroupBox(tab);
        groupBox_10->setObjectName(QStringLiteral("groupBox_10"));
        groupBox_10->setMinimumSize(QSize(215, 111));
        horizontalScrollBar_17 = new QScrollBar(groupBox_10);
        horizontalScrollBar_17->setObjectName(QStringLiteral("horizontalScrollBar_17"));
        horizontalScrollBar_17->setGeometry(QRect(50, 20, 120, 16));
        horizontalScrollBar_17->setMaximum(255);
        horizontalScrollBar_17->setSingleStep(1);
        horizontalScrollBar_17->setPageStep(10);
        horizontalScrollBar_17->setOrientation(Qt::Horizontal);
        horizontalScrollBar_18 = new QScrollBar(groupBox_10);
        horizontalScrollBar_18->setObjectName(QStringLiteral("horizontalScrollBar_18"));
        horizontalScrollBar_18->setGeometry(QRect(50, 42, 120, 16));
        horizontalScrollBar_18->setMaximum(255);
        horizontalScrollBar_18->setSingleStep(1);
        horizontalScrollBar_18->setPageStep(10);
        horizontalScrollBar_18->setOrientation(Qt::Horizontal);
        horizontalScrollBar_19 = new QScrollBar(groupBox_10);
        horizontalScrollBar_19->setObjectName(QStringLiteral("horizontalScrollBar_19"));
        horizontalScrollBar_19->setGeometry(QRect(50, 65, 120, 16));
        horizontalScrollBar_19->setMaximum(255);
        horizontalScrollBar_19->setSingleStep(1);
        horizontalScrollBar_19->setOrientation(Qt::Horizontal);
        horizontalScrollBar_20 = new QScrollBar(groupBox_10);
        horizontalScrollBar_20->setObjectName(QStringLiteral("horizontalScrollBar_20"));
        horizontalScrollBar_20->setGeometry(QRect(50, 86, 120, 16));
        horizontalScrollBar_20->setMaximum(255);
        horizontalScrollBar_20->setSingleStep(1);
        horizontalScrollBar_20->setOrientation(Qt::Horizontal);
        label_62 = new QLabel(groupBox_10);
        label_62->setObjectName(QStringLiteral("label_62"));
        label_62->setGeometry(QRect(173, 22, 21, 12));
        label_63 = new QLabel(groupBox_10);
        label_63->setObjectName(QStringLiteral("label_63"));
        label_63->setGeometry(QRect(173, 44, 21, 12));
        label_64 = new QLabel(groupBox_10);
        label_64->setObjectName(QStringLiteral("label_64"));
        label_64->setGeometry(QRect(173, 67, 21, 12));
        label_65 = new QLabel(groupBox_10);
        label_65->setObjectName(QStringLiteral("label_65"));
        label_65->setGeometry(QRect(173, 89, 21, 12));
        splitter_5 = new QSplitter(groupBox_10);
        splitter_5->setObjectName(QStringLiteral("splitter_5"));
        splitter_5->setGeometry(QRect(10, 20, 31, 81));
        splitter_5->setOrientation(Qt::Vertical);
        label_66 = new QLabel(splitter_5);
        label_66->setObjectName(QStringLiteral("label_66"));
        splitter_5->addWidget(label_66);
        label_67 = new QLabel(splitter_5);
        label_67->setObjectName(QStringLiteral("label_67"));
        splitter_5->addWidget(label_67);
        label_68 = new QLabel(splitter_5);
        label_68->setObjectName(QStringLiteral("label_68"));
        splitter_5->addWidget(label_68);
        label_69 = new QLabel(splitter_5);
        label_69->setObjectName(QStringLiteral("label_69"));
        splitter_5->addWidget(label_69);
        pushButton_3 = new QPushButton(groupBox_10);
        pushButton_3->setObjectName(QStringLiteral("pushButton_3"));
        pushButton_3->setGeometry(QRect(195, 20, 15, 81));
        pushButton_3->setStyleSheet(QStringLiteral("border:1px solid rgb(124,124,124);"));
        pushButton_3->setAutoDefault(false);
        pushButton_3->setDefault(false);
        pushButton_3->setFlat(false);

        horizontalLayout->addWidget(groupBox_10);

        groupBox_11 = new QGroupBox(tab);
        groupBox_11->setObjectName(QStringLiteral("groupBox_11"));
        groupBox_11->setMinimumSize(QSize(215, 111));
        horizontalScrollBar_21 = new QScrollBar(groupBox_11);
        horizontalScrollBar_21->setObjectName(QStringLiteral("horizontalScrollBar_21"));
        horizontalScrollBar_21->setGeometry(QRect(50, 20, 120, 16));
        horizontalScrollBar_21->setMaximum(255);
        horizontalScrollBar_21->setSingleStep(1);
        horizontalScrollBar_21->setPageStep(10);
        horizontalScrollBar_21->setOrientation(Qt::Horizontal);
        horizontalScrollBar_22 = new QScrollBar(groupBox_11);
        horizontalScrollBar_22->setObjectName(QStringLiteral("horizontalScrollBar_22"));
        horizontalScrollBar_22->setGeometry(QRect(50, 42, 120, 16));
        horizontalScrollBar_22->setMaximum(255);
        horizontalScrollBar_22->setSingleStep(1);
        horizontalScrollBar_22->setPageStep(10);
        horizontalScrollBar_22->setOrientation(Qt::Horizontal);
        horizontalScrollBar_23 = new QScrollBar(groupBox_11);
        horizontalScrollBar_23->setObjectName(QStringLiteral("horizontalScrollBar_23"));
        horizontalScrollBar_23->setGeometry(QRect(50, 65, 120, 16));
        horizontalScrollBar_23->setMaximum(255);
        horizontalScrollBar_23->setSingleStep(1);
        horizontalScrollBar_23->setOrientation(Qt::Horizontal);
        horizontalScrollBar_24 = new QScrollBar(groupBox_11);
        horizontalScrollBar_24->setObjectName(QStringLiteral("horizontalScrollBar_24"));
        horizontalScrollBar_24->setGeometry(QRect(50, 86, 120, 16));
        horizontalScrollBar_24->setMaximum(255);
        horizontalScrollBar_24->setSingleStep(1);
        horizontalScrollBar_24->setOrientation(Qt::Horizontal);
        label_70 = new QLabel(groupBox_11);
        label_70->setObjectName(QStringLiteral("label_70"));
        label_70->setGeometry(QRect(173, 22, 21, 12));
        label_71 = new QLabel(groupBox_11);
        label_71->setObjectName(QStringLiteral("label_71"));
        label_71->setGeometry(QRect(173, 44, 21, 12));
        label_72 = new QLabel(groupBox_11);
        label_72->setObjectName(QStringLiteral("label_72"));
        label_72->setGeometry(QRect(173, 67, 21, 12));
        label_73 = new QLabel(groupBox_11);
        label_73->setObjectName(QStringLiteral("label_73"));
        label_73->setGeometry(QRect(173, 89, 21, 12));
        splitter_6 = new QSplitter(groupBox_11);
        splitter_6->setObjectName(QStringLiteral("splitter_6"));
        splitter_6->setGeometry(QRect(10, 20, 31, 81));
        splitter_6->setOrientation(Qt::Vertical);
        label_74 = new QLabel(splitter_6);
        label_74->setObjectName(QStringLiteral("label_74"));
        splitter_6->addWidget(label_74);
        label_75 = new QLabel(splitter_6);
        label_75->setObjectName(QStringLiteral("label_75"));
        splitter_6->addWidget(label_75);
        label_76 = new QLabel(splitter_6);
        label_76->setObjectName(QStringLiteral("label_76"));
        splitter_6->addWidget(label_76);
        label_77 = new QLabel(splitter_6);
        label_77->setObjectName(QStringLiteral("label_77"));
        splitter_6->addWidget(label_77);
        pushButton_4 = new QPushButton(groupBox_11);
        pushButton_4->setObjectName(QStringLiteral("pushButton_4"));
        pushButton_4->setGeometry(QRect(195, 20, 15, 81));
        pushButton_4->setStyleSheet(QStringLiteral("border:1px solid rgb(124,124,124);"));
        pushButton_4->setAutoDefault(false);
        pushButton_4->setDefault(false);
        pushButton_4->setFlat(false);

        horizontalLayout->addWidget(groupBox_11);

        tabWidget->addTab(tab, QString());
        tab_2 = new QWidget();
        tab_2->setObjectName(QStringLiteral("tab_2"));
        horizontalLayout_2 = new QHBoxLayout(tab_2);
        horizontalLayout_2->setSpacing(6);
        horizontalLayout_2->setContentsMargins(11, 11, 11, 11);
        horizontalLayout_2->setObjectName(QStringLiteral("horizontalLayout_2"));
        groupBox_8 = new QGroupBox(tab_2);
        groupBox_8->setObjectName(QStringLiteral("groupBox_8"));
        groupBox_8->setMinimumSize(QSize(215, 111));
        horizontalScrollBar_9 = new QScrollBar(groupBox_8);
        horizontalScrollBar_9->setObjectName(QStringLiteral("horizontalScrollBar_9"));
        horizontalScrollBar_9->setGeometry(QRect(50, 20, 120, 16));
        horizontalScrollBar_9->setMaximum(255);
        horizontalScrollBar_9->setSingleStep(1);
        horizontalScrollBar_9->setPageStep(10);
        horizontalScrollBar_9->setOrientation(Qt::Horizontal);
        horizontalScrollBar_10 = new QScrollBar(groupBox_8);
        horizontalScrollBar_10->setObjectName(QStringLiteral("horizontalScrollBar_10"));
        horizontalScrollBar_10->setGeometry(QRect(50, 42, 120, 16));
        horizontalScrollBar_10->setMaximum(255);
        horizontalScrollBar_10->setSingleStep(1);
        horizontalScrollBar_10->setPageStep(10);
        horizontalScrollBar_10->setOrientation(Qt::Horizontal);
        horizontalScrollBar_11 = new QScrollBar(groupBox_8);
        horizontalScrollBar_11->setObjectName(QStringLiteral("horizontalScrollBar_11"));
        horizontalScrollBar_11->setGeometry(QRect(50, 65, 120, 16));
        horizontalScrollBar_11->setMaximum(255);
        horizontalScrollBar_11->setSingleStep(1);
        horizontalScrollBar_11->setOrientation(Qt::Horizontal);
        horizontalScrollBar_12 = new QScrollBar(groupBox_8);
        horizontalScrollBar_12->setObjectName(QStringLiteral("horizontalScrollBar_12"));
        horizontalScrollBar_12->setGeometry(QRect(50, 86, 120, 16));
        horizontalScrollBar_12->setMaximum(255);
        horizontalScrollBar_12->setSingleStep(1);
        horizontalScrollBar_12->setOrientation(Qt::Horizontal);
        label_46 = new QLabel(groupBox_8);
        label_46->setObjectName(QStringLiteral("label_46"));
        label_46->setGeometry(QRect(173, 22, 21, 12));
        label_47 = new QLabel(groupBox_8);
        label_47->setObjectName(QStringLiteral("label_47"));
        label_47->setGeometry(QRect(173, 44, 21, 12));
        label_48 = new QLabel(groupBox_8);
        label_48->setObjectName(QStringLiteral("label_48"));
        label_48->setGeometry(QRect(173, 67, 21, 12));
        label_49 = new QLabel(groupBox_8);
        label_49->setObjectName(QStringLiteral("label_49"));
        label_49->setGeometry(QRect(173, 89, 21, 12));
        splitter_3 = new QSplitter(groupBox_8);
        splitter_3->setObjectName(QStringLiteral("splitter_3"));
        splitter_3->setGeometry(QRect(10, 20, 31, 81));
        splitter_3->setOrientation(Qt::Vertical);
        label_50 = new QLabel(splitter_3);
        label_50->setObjectName(QStringLiteral("label_50"));
        splitter_3->addWidget(label_50);
        label_51 = new QLabel(splitter_3);
        label_51->setObjectName(QStringLiteral("label_51"));
        splitter_3->addWidget(label_51);
        label_52 = new QLabel(splitter_3);
        label_52->setObjectName(QStringLiteral("label_52"));
        splitter_3->addWidget(label_52);
        label_53 = new QLabel(splitter_3);
        label_53->setObjectName(QStringLiteral("label_53"));
        splitter_3->addWidget(label_53);
        pushButton_5 = new QPushButton(groupBox_8);
        pushButton_5->setObjectName(QStringLiteral("pushButton_5"));
        pushButton_5->setGeometry(QRect(195, 20, 15, 81));
        pushButton_5->setStyleSheet(QStringLiteral("border:1px solid rgb(124,124,124);"));
        pushButton_5->setAutoDefault(false);
        pushButton_5->setDefault(false);
        pushButton_5->setFlat(false);

        horizontalLayout_2->addWidget(groupBox_8);

        groupBox_9 = new QGroupBox(tab_2);
        groupBox_9->setObjectName(QStringLiteral("groupBox_9"));
        groupBox_9->setMinimumSize(QSize(215, 111));
        horizontalScrollBar_13 = new QScrollBar(groupBox_9);
        horizontalScrollBar_13->setObjectName(QStringLiteral("horizontalScrollBar_13"));
        horizontalScrollBar_13->setGeometry(QRect(50, 20, 120, 16));
        horizontalScrollBar_13->setMaximum(255);
        horizontalScrollBar_13->setSingleStep(1);
        horizontalScrollBar_13->setPageStep(10);
        horizontalScrollBar_13->setOrientation(Qt::Horizontal);
        horizontalScrollBar_14 = new QScrollBar(groupBox_9);
        horizontalScrollBar_14->setObjectName(QStringLiteral("horizontalScrollBar_14"));
        horizontalScrollBar_14->setGeometry(QRect(50, 42, 120, 16));
        horizontalScrollBar_14->setMaximum(255);
        horizontalScrollBar_14->setSingleStep(1);
        horizontalScrollBar_14->setPageStep(10);
        horizontalScrollBar_14->setOrientation(Qt::Horizontal);
        horizontalScrollBar_15 = new QScrollBar(groupBox_9);
        horizontalScrollBar_15->setObjectName(QStringLiteral("horizontalScrollBar_15"));
        horizontalScrollBar_15->setGeometry(QRect(50, 65, 120, 16));
        horizontalScrollBar_15->setMaximum(255);
        horizontalScrollBar_15->setSingleStep(1);
        horizontalScrollBar_15->setOrientation(Qt::Horizontal);
        horizontalScrollBar_16 = new QScrollBar(groupBox_9);
        horizontalScrollBar_16->setObjectName(QStringLiteral("horizontalScrollBar_16"));
        horizontalScrollBar_16->setGeometry(QRect(50, 86, 120, 16));
        horizontalScrollBar_16->setMaximum(255);
        horizontalScrollBar_16->setSingleStep(1);
        horizontalScrollBar_16->setOrientation(Qt::Horizontal);
        label_54 = new QLabel(groupBox_9);
        label_54->setObjectName(QStringLiteral("label_54"));
        label_54->setGeometry(QRect(173, 22, 21, 12));
        label_55 = new QLabel(groupBox_9);
        label_55->setObjectName(QStringLiteral("label_55"));
        label_55->setGeometry(QRect(173, 44, 21, 12));
        label_56 = new QLabel(groupBox_9);
        label_56->setObjectName(QStringLiteral("label_56"));
        label_56->setGeometry(QRect(173, 67, 21, 12));
        label_57 = new QLabel(groupBox_9);
        label_57->setObjectName(QStringLiteral("label_57"));
        label_57->setGeometry(QRect(173, 89, 21, 12));
        splitter_4 = new QSplitter(groupBox_9);
        splitter_4->setObjectName(QStringLiteral("splitter_4"));
        splitter_4->setGeometry(QRect(10, 20, 31, 81));
        splitter_4->setOrientation(Qt::Vertical);
        label_58 = new QLabel(splitter_4);
        label_58->setObjectName(QStringLiteral("label_58"));
        splitter_4->addWidget(label_58);
        label_59 = new QLabel(splitter_4);
        label_59->setObjectName(QStringLiteral("label_59"));
        splitter_4->addWidget(label_59);
        label_60 = new QLabel(splitter_4);
        label_60->setObjectName(QStringLiteral("label_60"));
        splitter_4->addWidget(label_60);
        label_61 = new QLabel(splitter_4);
        label_61->setObjectName(QStringLiteral("label_61"));
        splitter_4->addWidget(label_61);
        pushButton_6 = new QPushButton(groupBox_9);
        pushButton_6->setObjectName(QStringLiteral("pushButton_6"));
        pushButton_6->setGeometry(QRect(195, 20, 15, 81));
        pushButton_6->setStyleSheet(QStringLiteral("border:1px solid rgb(124,124,124);"));
        pushButton_6->setAutoDefault(false);
        pushButton_6->setDefault(false);
        pushButton_6->setFlat(false);

        horizontalLayout_2->addWidget(groupBox_9);

        tabWidget->addTab(tab_2, QString());
        tab_3 = new QWidget();
        tab_3->setObjectName(QStringLiteral("tab_3"));
        horizontalLayout_3 = new QHBoxLayout(tab_3);
        horizontalLayout_3->setSpacing(6);
        horizontalLayout_3->setContentsMargins(11, 11, 11, 11);
        horizontalLayout_3->setObjectName(QStringLiteral("horizontalLayout_3"));
        groupBox_6 = new QGroupBox(tab_3);
        groupBox_6->setObjectName(QStringLiteral("groupBox_6"));
        groupBox_6->setMinimumSize(QSize(215, 111));
        horizontalScrollBar = new QScrollBar(groupBox_6);
        horizontalScrollBar->setObjectName(QStringLiteral("horizontalScrollBar"));
        horizontalScrollBar->setGeometry(QRect(50, 20, 120, 16));
        horizontalScrollBar->setMaximum(255);
        horizontalScrollBar->setSingleStep(1);
        horizontalScrollBar->setPageStep(10);
        horizontalScrollBar->setOrientation(Qt::Horizontal);
        horizontalScrollBar_2 = new QScrollBar(groupBox_6);
        horizontalScrollBar_2->setObjectName(QStringLiteral("horizontalScrollBar_2"));
        horizontalScrollBar_2->setGeometry(QRect(50, 42, 120, 16));
        horizontalScrollBar_2->setMaximum(255);
        horizontalScrollBar_2->setSingleStep(1);
        horizontalScrollBar_2->setPageStep(10);
        horizontalScrollBar_2->setOrientation(Qt::Horizontal);
        horizontalScrollBar_3 = new QScrollBar(groupBox_6);
        horizontalScrollBar_3->setObjectName(QStringLiteral("horizontalScrollBar_3"));
        horizontalScrollBar_3->setGeometry(QRect(50, 65, 120, 16));
        horizontalScrollBar_3->setMaximum(255);
        horizontalScrollBar_3->setSingleStep(1);
        horizontalScrollBar_3->setOrientation(Qt::Horizontal);
        horizontalScrollBar_4 = new QScrollBar(groupBox_6);
        horizontalScrollBar_4->setObjectName(QStringLiteral("horizontalScrollBar_4"));
        horizontalScrollBar_4->setGeometry(QRect(50, 86, 120, 16));
        horizontalScrollBar_4->setMaximum(255);
        horizontalScrollBar_4->setSingleStep(1);
        horizontalScrollBar_4->setOrientation(Qt::Horizontal);
        label_26 = new QLabel(groupBox_6);
        label_26->setObjectName(QStringLiteral("label_26"));
        label_26->setGeometry(QRect(173, 22, 21, 12));
        label_27 = new QLabel(groupBox_6);
        label_27->setObjectName(QStringLiteral("label_27"));
        label_27->setGeometry(QRect(173, 44, 21, 12));
        label_36 = new QLabel(groupBox_6);
        label_36->setObjectName(QStringLiteral("label_36"));
        label_36->setGeometry(QRect(173, 67, 21, 12));
        label_37 = new QLabel(groupBox_6);
        label_37->setObjectName(QStringLiteral("label_37"));
        label_37->setGeometry(QRect(173, 89, 21, 12));
        splitter = new QSplitter(groupBox_6);
        splitter->setObjectName(QStringLiteral("splitter"));
        splitter->setGeometry(QRect(10, 20, 31, 81));
        splitter->setOrientation(Qt::Vertical);
        label_22 = new QLabel(splitter);
        label_22->setObjectName(QStringLiteral("label_22"));
        splitter->addWidget(label_22);
        label_23 = new QLabel(splitter);
        label_23->setObjectName(QStringLiteral("label_23"));
        splitter->addWidget(label_23);
        label_24 = new QLabel(splitter);
        label_24->setObjectName(QStringLiteral("label_24"));
        splitter->addWidget(label_24);
        label_25 = new QLabel(splitter);
        label_25->setObjectName(QStringLiteral("label_25"));
        splitter->addWidget(label_25);
        pushButton_7 = new QPushButton(groupBox_6);
        pushButton_7->setObjectName(QStringLiteral("pushButton_7"));
        pushButton_7->setGeometry(QRect(195, 20, 15, 81));
        pushButton_7->setStyleSheet(QStringLiteral("border:1px solid rgb(124,124,124);"));
        pushButton_7->setAutoDefault(false);
        pushButton_7->setDefault(false);
        pushButton_7->setFlat(false);

        horizontalLayout_3->addWidget(groupBox_6);

        groupBox_7 = new QGroupBox(tab_3);
        groupBox_7->setObjectName(QStringLiteral("groupBox_7"));
        groupBox_7->setMinimumSize(QSize(215, 111));
        label_87 = new QLabel(groupBox_7);
        label_87->setObjectName(QStringLiteral("label_87"));
        label_87->setGeometry(QRect(10, 19, 95, 78));
        label_87->setStyleSheet(QLatin1String("background-color: rgb(190,190,190);\n"
"border-radius: 10px;\n"
"border-width: 2px;\n"
"border-style: groove;\n"
"border-color:rgb(80,80,80)"));
        label_87->setFrameShape(QFrame::NoFrame);
        label_87->setAlignment(Qt::AlignCenter);
        pushButton = new QPushButton(groupBox_7);
        pushButton->setObjectName(QStringLiteral("pushButton"));
        pushButton->setGeometry(QRect(120, 18, 80, 26));
        checkBox = new QCheckBox(groupBox_7);
        checkBox->setObjectName(QStringLiteral("checkBox"));
        checkBox->setGeometry(QRect(120, 54, 75, 16));
        checkBox->setCheckable(true);
        checkBox->setChecked(false);
        checkBox_2 = new QCheckBox(groupBox_7);
        checkBox_2->setObjectName(QStringLiteral("checkBox_2"));
        checkBox_2->setGeometry(QRect(120, 80, 75, 16));

        horizontalLayout_3->addWidget(groupBox_7);

        tabWidget->addTab(tab_3, QString());

        verticalLayout->addWidget(tabWidget);

        QtApplicationClass->setCentralWidget(centralWidget);
        tabWidget->raise();
        widget_2->raise();
        menuBar = new QMenuBar(QtApplicationClass);
        menuBar->setObjectName(QStringLiteral("menuBar"));
        menuBar->setGeometry(QRect(0, 0, 1000, 23));
        menu_File = new QMenu(menuBar);
        menu_File->setObjectName(QStringLiteral("menu_File"));
        menu_History = new QMenu(menu_File);
        menu_History->setObjectName(QStringLiteral("menu_History"));
        menu_View = new QMenu(menuBar);
        menu_View->setObjectName(QStringLiteral("menu_View"));
        menu_Window = new QMenu(menuBar);
        menu_Window->setObjectName(QStringLiteral("menu_Window"));
        menu_Example = new QMenu(menuBar);
        menu_Example->setObjectName(QStringLiteral("menu_Example"));
        menu_Help = new QMenu(menuBar);
        menu_Help->setObjectName(QStringLiteral("menu_Help"));
        QtApplicationClass->setMenuBar(menuBar);
        mainToolBar = new QToolBar(QtApplicationClass);
        mainToolBar->setObjectName(QStringLiteral("mainToolBar"));
        mainToolBar->setEnabled(true);
        mainToolBar->setLayoutDirection(Qt::LeftToRight);
        mainToolBar->setAutoFillBackground(true);
        mainToolBar->setMovable(true);
        mainToolBar->setAllowedAreas(Qt::AllToolBarAreas);
        mainToolBar->setIconSize(QSize(28, 28));
        mainToolBar->setToolButtonStyle(Qt::ToolButtonTextUnderIcon);
        mainToolBar->setFloatable(true);
        QtApplicationClass->addToolBar(Qt::TopToolBarArea, mainToolBar);
        Properties = new QDockWidget(QtApplicationClass);
        Properties->setObjectName(QStringLiteral("Properties"));
        Properties->setMinimumSize(QSize(257, 529));
        Properties->setFeatures(QDockWidget::DockWidgetFloatable|QDockWidget::DockWidgetMovable);
        dockWidgetContents = new QWidget();
        dockWidgetContents->setObjectName(QStringLiteral("dockWidgetContents"));
        label = new QLabel(dockWidgetContents);
        label->setObjectName(QStringLiteral("label"));
        label->setGeometry(QRect(14, 4, 91, 21));
        line = new QFrame(dockWidgetContents);
        line->setObjectName(QStringLiteral("line"));
        line->setEnabled(true);
        line->setGeometry(QRect(10, 22, 241, 16));
        line->setFrameShadow(QFrame::Sunken);
        line->setLineWidth(1);
        line->setFrameShape(QFrame::HLine);
        dial = new QDial(dockWidgetContents);
        dial->setObjectName(QStringLiteral("dial"));
        dial->setGeometry(QRect(120, -2, 41, 31));
        dial->setMinimum(-1);
        dial->setMaximum(10);
        dial->setValue(-1);
        dial->setOrientation(Qt::Horizontal);
        doubleSpinBox = new QDoubleSpinBox(dockWidgetContents);
        doubleSpinBox->setObjectName(QStringLiteral("doubleSpinBox"));
        doubleSpinBox->setGeometry(QRect(160, 4, 80, 22));
        doubleSpinBox->setDecimals(2);
        doubleSpinBox->setMinimum(-1);
        doubleSpinBox->setMaximum(100);
        doubleSpinBox->setSingleStep(0.1);
        line_2 = new QFrame(dockWidgetContents);
        line_2->setObjectName(QStringLiteral("line_2"));
        line_2->setGeometry(QRect(10, 55, 241, 16));
        line_2->setFrameShape(QFrame::HLine);
        line_2->setFrameShadow(QFrame::Sunken);
        dial_2 = new QDial(dockWidgetContents);
        dial_2->setObjectName(QStringLiteral("dial_2"));
        dial_2->setGeometry(QRect(120, 31, 41, 31));
        dial_2->setMaximum(2000);
        label_2 = new QLabel(dockWidgetContents);
        label_2->setObjectName(QStringLiteral("label_2"));
        label_2->setGeometry(QRect(14, 39, 101, 20));
        doubleSpinBox_2 = new QDoubleSpinBox(dockWidgetContents);
        doubleSpinBox_2->setObjectName(QStringLiteral("doubleSpinBox_2"));
        doubleSpinBox_2->setGeometry(QRect(160, 37, 80, 22));
        doubleSpinBox_2->setMaximum(2000);
        doubleSpinBox_2->setSingleStep(20);
        line_3 = new QFrame(dockWidgetContents);
        line_3->setObjectName(QStringLiteral("line_3"));
        line_3->setGeometry(QRect(10, 90, 241, 16));
        line_3->setFrameShape(QFrame::HLine);
        line_3->setFrameShadow(QFrame::Sunken);
        label_3 = new QLabel(dockWidgetContents);
        label_3->setObjectName(QStringLiteral("label_3"));
        label_3->setGeometry(QRect(14, 65, 81, 31));
        dial_3 = new QDial(dockWidgetContents);
        dial_3->setObjectName(QStringLiteral("dial_3"));
        dial_3->setGeometry(QRect(120, 66, 41, 31));
        dial_3->setMaximum(10);
        doubleSpinBox_3 = new QDoubleSpinBox(dockWidgetContents);
        doubleSpinBox_3->setObjectName(QStringLiteral("doubleSpinBox_3"));
        doubleSpinBox_3->setGeometry(QRect(160, 73, 80, 22));
        doubleSpinBox_3->setMaximum(10);
        doubleSpinBox_3->setSingleStep(0.1);
        doubleSpinBox_4 = new QDoubleSpinBox(dockWidgetContents);
        doubleSpinBox_4->setObjectName(QStringLiteral("doubleSpinBox_4"));
        doubleSpinBox_4->setGeometry(QRect(160, 108, 80, 22));
        doubleSpinBox_4->setMaximum(10);
        doubleSpinBox_4->setSingleStep(0.1);
        label_4 = new QLabel(dockWidgetContents);
        label_4->setObjectName(QStringLiteral("label_4"));
        label_4->setGeometry(QRect(14, 101, 71, 31));
        line_4 = new QFrame(dockWidgetContents);
        line_4->setObjectName(QStringLiteral("line_4"));
        line_4->setGeometry(QRect(10, 128, 241, 16));
        line_4->setFrameShape(QFrame::HLine);
        line_4->setFrameShadow(QFrame::Sunken);
        dial_4 = new QDial(dockWidgetContents);
        dial_4->setObjectName(QStringLiteral("dial_4"));
        dial_4->setGeometry(QRect(120, 102, 41, 31));
        dial_4->setMaximum(10);
        dial_4->setSingleStep(1);
        line_5 = new QFrame(dockWidgetContents);
        line_5->setObjectName(QStringLiteral("line_5"));
        line_5->setGeometry(QRect(10, 160, 241, 16));
        line_5->setFrameShape(QFrame::HLine);
        line_5->setFrameShadow(QFrame::Sunken);
        label_5 = new QLabel(dockWidgetContents);
        label_5->setObjectName(QStringLiteral("label_5"));
        label_5->setGeometry(QRect(14, 145, 81, 16));
        dial_5 = new QDial(dockWidgetContents);
        dial_5->setObjectName(QStringLiteral("dial_5"));
        dial_5->setGeometry(QRect(120, 136, 41, 31));
        dial_5->setMaximum(300);
        doubleSpinBox_5 = new QDoubleSpinBox(dockWidgetContents);
        doubleSpinBox_5->setObjectName(QStringLiteral("doubleSpinBox_5"));
        doubleSpinBox_5->setGeometry(QRect(160, 141, 80, 22));
        doubleSpinBox_5->setMaximum(300);
        doubleSpinBox_5->setSingleStep(3);
        line_6 = new QFrame(dockWidgetContents);
        line_6->setObjectName(QStringLiteral("line_6"));
        line_6->setGeometry(QRect(10, 190, 241, 16));
        line_6->setFrameShape(QFrame::HLine);
        line_6->setFrameShadow(QFrame::Sunken);
        doubleSpinBox_6 = new QDoubleSpinBox(dockWidgetContents);
        doubleSpinBox_6->setObjectName(QStringLiteral("doubleSpinBox_6"));
        doubleSpinBox_6->setGeometry(QRect(160, 171, 80, 22));
        doubleSpinBox_6->setMaximum(300);
        doubleSpinBox_6->setSingleStep(3);
        label_6 = new QLabel(dockWidgetContents);
        label_6->setObjectName(QStringLiteral("label_6"));
        label_6->setGeometry(QRect(14, 175, 91, 16));
        dial_6 = new QDial(dockWidgetContents);
        dial_6->setObjectName(QStringLiteral("dial_6"));
        dial_6->setGeometry(QRect(120, 166, 41, 31));
        dial_6->setMaximum(300);
        line_7 = new QFrame(dockWidgetContents);
        line_7->setObjectName(QStringLiteral("line_7"));
        line_7->setGeometry(QRect(10, 220, 241, 16));
        line_7->setFrameShape(QFrame::HLine);
        line_7->setFrameShadow(QFrame::Sunken);
        label_7 = new QLabel(dockWidgetContents);
        label_7->setObjectName(QStringLiteral("label_7"));
        label_7->setGeometry(QRect(14, 201, 91, 21));
        doubleSpinBox_7 = new QDoubleSpinBox(dockWidgetContents);
        doubleSpinBox_7->setObjectName(QStringLiteral("doubleSpinBox_7"));
        doubleSpinBox_7->setGeometry(QRect(160, 202, 80, 22));
        doubleSpinBox_7->setMaximum(300);
        doubleSpinBox_7->setSingleStep(3);
        dial_7 = new QDial(dockWidgetContents);
        dial_7->setObjectName(QStringLiteral("dial_7"));
        dial_7->setGeometry(QRect(120, 197, 41, 31));
        dial_7->setMaximum(300);
        line_8 = new QFrame(dockWidgetContents);
        line_8->setObjectName(QStringLiteral("line_8"));
        line_8->setGeometry(QRect(10, 250, 241, 16));
        line_8->setFrameShape(QFrame::HLine);
        line_8->setFrameShadow(QFrame::Sunken);
        doubleSpinBox_8 = new QDoubleSpinBox(dockWidgetContents);
        doubleSpinBox_8->setObjectName(QStringLiteral("doubleSpinBox_8"));
        doubleSpinBox_8->setGeometry(QRect(160, 232, 80, 22));
        doubleSpinBox_8->setMaximum(300);
        doubleSpinBox_8->setSingleStep(3);
        label_8 = new QLabel(dockWidgetContents);
        label_8->setObjectName(QStringLiteral("label_8"));
        label_8->setGeometry(QRect(14, 230, 91, 21));
        dial_8 = new QDial(dockWidgetContents);
        dial_8->setObjectName(QStringLiteral("dial_8"));
        dial_8->setGeometry(QRect(120, 227, 41, 31));
        dial_8->setMaximum(300);
        doubleSpinBox_14 = new QDoubleSpinBox(dockWidgetContents);
        doubleSpinBox_14->setObjectName(QStringLiteral("doubleSpinBox_14"));
        doubleSpinBox_14->setGeometry(QRect(160, 262, 80, 22));
        doubleSpinBox_14->setMaximum(360);
        doubleSpinBox_14->setSingleStep(3);
        label_14 = new QLabel(dockWidgetContents);
        label_14->setObjectName(QStringLiteral("label_14"));
        label_14->setGeometry(QRect(14, 260, 91, 21));
        dial_14 = new QDial(dockWidgetContents);
        dial_14->setObjectName(QStringLiteral("dial_14"));
        dial_14->setGeometry(QRect(120, 257, 41, 31));
        dial_14->setMaximum(360);
        line_14 = new QFrame(dockWidgetContents);
        line_14->setObjectName(QStringLiteral("line_14"));
        line_14->setGeometry(QRect(10, 280, 241, 16));
        line_14->setFrameShape(QFrame::HLine);
        line_14->setFrameShadow(QFrame::Sunken);
        line_15 = new QFrame(dockWidgetContents);
        line_15->setObjectName(QStringLiteral("line_15"));
        line_15->setGeometry(QRect(10, 310, 241, 16));
        line_15->setFrameShape(QFrame::HLine);
        line_15->setFrameShadow(QFrame::Sunken);
        dial_15 = new QDial(dockWidgetContents);
        dial_15->setObjectName(QStringLiteral("dial_15"));
        dial_15->setGeometry(QRect(120, 287, 41, 31));
        dial_15->setMaximum(360);
        doubleSpinBox_15 = new QDoubleSpinBox(dockWidgetContents);
        doubleSpinBox_15->setObjectName(QStringLiteral("doubleSpinBox_15"));
        doubleSpinBox_15->setGeometry(QRect(160, 293, 80, 22));
        doubleSpinBox_15->setMaximum(360);
        doubleSpinBox_15->setSingleStep(3);
        label_15 = new QLabel(dockWidgetContents);
        label_15->setObjectName(QStringLiteral("label_15"));
        label_15->setGeometry(QRect(14, 292, 91, 21));
        line_16 = new QFrame(dockWidgetContents);
        line_16->setObjectName(QStringLiteral("line_16"));
        line_16->setGeometry(QRect(10, 340, 241, 16));
        line_16->setFrameShape(QFrame::HLine);
        line_16->setFrameShadow(QFrame::Sunken);
        dial_16 = new QDial(dockWidgetContents);
        dial_16->setObjectName(QStringLiteral("dial_16"));
        dial_16->setGeometry(QRect(120, 317, 41, 31));
        dial_16->setMaximum(360);
        doubleSpinBox_16 = new QDoubleSpinBox(dockWidgetContents);
        doubleSpinBox_16->setObjectName(QStringLiteral("doubleSpinBox_16"));
        doubleSpinBox_16->setGeometry(QRect(160, 322, 80, 22));
        doubleSpinBox_16->setMaximum(360);
        doubleSpinBox_16->setSingleStep(3);
        label_16 = new QLabel(dockWidgetContents);
        label_16->setObjectName(QStringLiteral("label_16"));
        label_16->setGeometry(QRect(14, 321, 91, 21));
        doubleSpinBox_17 = new QDoubleSpinBox(dockWidgetContents);
        doubleSpinBox_17->setObjectName(QStringLiteral("doubleSpinBox_17"));
        doubleSpinBox_17->setGeometry(QRect(160, 358, 80, 22));
        doubleSpinBox_17->setMaximum(360);
        doubleSpinBox_17->setSingleStep(3);
        label_17 = new QLabel(dockWidgetContents);
        label_17->setObjectName(QStringLiteral("label_17"));
        label_17->setGeometry(QRect(14, 346, 91, 41));
        line_17 = new QFrame(dockWidgetContents);
        line_17->setObjectName(QStringLiteral("line_17"));
        line_17->setGeometry(QRect(10, 380, 241, 16));
        line_17->setFrameShape(QFrame::HLine);
        line_17->setFrameShadow(QFrame::Sunken);
        dial_17 = new QDial(dockWidgetContents);
        dial_17->setObjectName(QStringLiteral("dial_17"));
        dial_17->setGeometry(QRect(120, 353, 41, 31));
        dial_17->setMaximum(360);
        line_18 = new QFrame(dockWidgetContents);
        line_18->setObjectName(QStringLiteral("line_18"));
        line_18->setGeometry(QRect(10, 420, 241, 16));
        line_18->setFrameShape(QFrame::HLine);
        line_18->setFrameShadow(QFrame::Sunken);
        label_18 = new QLabel(dockWidgetContents);
        label_18->setObjectName(QStringLiteral("label_18"));
        label_18->setGeometry(QRect(14, 386, 91, 41));
        doubleSpinBox_18 = new QDoubleSpinBox(dockWidgetContents);
        doubleSpinBox_18->setObjectName(QStringLiteral("doubleSpinBox_18"));
        doubleSpinBox_18->setGeometry(QRect(160, 398, 80, 22));
        doubleSpinBox_18->setMaximum(360);
        doubleSpinBox_18->setSingleStep(3);
        dial_18 = new QDial(dockWidgetContents);
        dial_18->setObjectName(QStringLiteral("dial_18"));
        dial_18->setGeometry(QRect(120, 393, 41, 31));
        dial_18->setMaximum(360);
        line_19 = new QFrame(dockWidgetContents);
        line_19->setObjectName(QStringLiteral("line_19"));
        line_19->setGeometry(QRect(10, 460, 261, 16));
        line_19->setFrameShape(QFrame::HLine);
        line_19->setFrameShadow(QFrame::Sunken);
        doubleSpinBox_19 = new QDoubleSpinBox(dockWidgetContents);
        doubleSpinBox_19->setObjectName(QStringLiteral("doubleSpinBox_19"));
        doubleSpinBox_19->setGeometry(QRect(160, 438, 80, 22));
        doubleSpinBox_19->setMaximum(360);
        doubleSpinBox_19->setSingleStep(3);
        dial_19 = new QDial(dockWidgetContents);
        dial_19->setObjectName(QStringLiteral("dial_19"));
        dial_19->setGeometry(QRect(120, 433, 41, 31));
        dial_19->setMaximum(360);
        label_19 = new QLabel(dockWidgetContents);
        label_19->setObjectName(QStringLiteral("label_19"));
        label_19->setGeometry(QRect(14, 426, 91, 41));
        Properties->setWidget(dockWidgetContents);
        QtApplicationClass->addDockWidget(static_cast<Qt::DockWidgetArea>(1), Properties);
        Blend = new QDockWidget(QtApplicationClass);
        Blend->setObjectName(QStringLiteral("Blend"));
        Blend->setMinimumSize(QSize(257, 90));
        Blend->setMaximumSize(QSize(524287, 125));
        Blend->setAutoFillBackground(false);
        Blend->setFeatures(QDockWidget::DockWidgetFloatable|QDockWidget::DockWidgetMovable);
        Blend->setAllowedAreas(Qt::AllDockWidgetAreas);
        dockWidgetContents_2 = new QWidget();
        dockWidgetContents_2->setObjectName(QStringLiteral("dockWidgetContents_2"));
        label_20 = new QLabel(dockWidgetContents_2);
        label_20->setObjectName(QStringLiteral("label_20"));
        label_20->setGeometry(QRect(10, 10, 54, 21));
        comboBox = new QComboBox(dockWidgetContents_2);
        comboBox->setObjectName(QStringLiteral("comboBox"));
        comboBox->setGeometry(QRect(31, 10, 163, 22));
        btn_normal = new QPushButton(dockWidgetContents_2);
        btn_normal->setObjectName(QStringLiteral("btn_normal"));
        btn_normal->setGeometry(QRect(200, 9, 57, 24));
        label_21 = new QLabel(dockWidgetContents_2);
        label_21->setObjectName(QStringLiteral("label_21"));
        label_21->setGeometry(QRect(10, 40, 54, 21));
        pushButton_2 = new QPushButton(dockWidgetContents_2);
        pushButton_2->setObjectName(QStringLiteral("pushButton_2"));
        pushButton_2->setGeometry(QRect(200, 39, 57, 24));
        comboBox_2 = new QComboBox(dockWidgetContents_2);
        comboBox_2->setObjectName(QStringLiteral("comboBox_2"));
        comboBox_2->setGeometry(QRect(31, 39, 163, 22));
        Blend->setWidget(dockWidgetContents_2);
        QtApplicationClass->addDockWidget(static_cast<Qt::DockWidgetArea>(1), Blend);
        dockWidget = new QDockWidget(QtApplicationClass);
        dockWidget->setObjectName(QStringLiteral("dockWidget"));
        dockWidget->setMinimumSize(QSize(257, 120));
        dockWidget->setMaximumSize(QSize(257, 120));
        dockWidget->setFocusPolicy(Qt::NoFocus);
        dockWidget->setLayoutDirection(Qt::LeftToRight);
        dockWidget->setAutoFillBackground(true);
        dockWidget->setFloating(false);
        dockWidget->setFeatures(QDockWidget::NoDockWidgetFeatures);
        dockWidget->setAllowedAreas(Qt::RightDockWidgetArea);
        dockWidgetContents_3 = new QWidget();
        dockWidgetContents_3->setObjectName(QStringLiteral("dockWidgetContents_3"));
        widget = new QWidget(dockWidgetContents_3);
        widget->setObjectName(QStringLiteral("widget"));
        widget->setGeometry(QRect(20, 8, 91, 81));
        widget->setStyleSheet(QLatin1String("background-color: rgb(190,190,190);\n"
"border-radius: 10px;\n"
"border-width: 2px;\n"
"border-style: groove;\n"
"border-color:rgb(80,80,80)"));
        label_86 = new QLabel(widget);
        label_86->setObjectName(QStringLiteral("label_86"));
        label_86->setGeometry(QRect(10, 9, 71, 63));
        label_86->setStyleSheet(QStringLiteral("background-color: rgb(120,120,120)"));
        label_86->setFrameShape(QFrame::NoFrame);
        label_86->setAlignment(Qt::AlignCenter);
        choose_texture = new QPushButton(dockWidgetContents_3);
        choose_texture->setObjectName(QStringLiteral("choose_texture"));
        choose_texture->setGeometry(QRect(140, 63, 75, 26));
        choose_texture->setStyleSheet(QStringLiteral(""));
        dockWidget->setWidget(dockWidgetContents_3);
        QtApplicationClass->addDockWidget(static_cast<Qt::DockWidgetArea>(2), dockWidget);
        dockWidget_2 = new QDockWidget(QtApplicationClass);
        dockWidget_2->setObjectName(QStringLiteral("dockWidget_2"));
        dockWidget_2->setMinimumSize(QSize(257, 507));
        dockWidget_2->setMaximumSize(QSize(257, 524287));
        dockWidget_2->setToolTipDuration(-1);
        dockWidget_2->setInputMethodHints(Qt::ImhNone);
        dockWidget_2->setFloating(false);
        dockWidget_2->setFeatures(QDockWidget::DockWidgetFloatable|QDockWidget::DockWidgetMovable);
        dockWidgetContents_5 = new QWidget();
        dockWidgetContents_5->setObjectName(QStringLiteral("dockWidgetContents_5"));
        dockWidgetContents_5->setMaximumSize(QSize(16777215, 16777215));
        verticalLayout_2 = new QVBoxLayout(dockWidgetContents_5);
        verticalLayout_2->setSpacing(6);
        verticalLayout_2->setContentsMargins(11, 11, 11, 11);
        verticalLayout_2->setObjectName(QStringLiteral("verticalLayout_2"));
        frame = new QFrame(dockWidgetContents_5);
        frame->setObjectName(QStringLiteral("frame"));
        frame->setMinimumSize(QSize(0, 311));
        frame->setFrameShape(QFrame::StyledPanel);
        frame->setFrameShadow(QFrame::Raised);
        scrollArea_2 = new QScrollArea(frame);
        scrollArea_2->setObjectName(QStringLiteral("scrollArea_2"));
        scrollArea_2->setGeometry(QRect(0, 0, 241, 34));
        scrollArea_2->setWidgetResizable(true);
        scrollAreaWidgetContents_2 = new QWidget();
        scrollAreaWidgetContents_2->setObjectName(QStringLiteral("scrollAreaWidgetContents_2"));
        scrollAreaWidgetContents_2->setGeometry(QRect(0, 0, 239, 32));
        label_31 = new QLabel(scrollAreaWidgetContents_2);
        label_31->setObjectName(QStringLiteral("label_31"));
        label_31->setGeometry(QRect(12, 5, 71, 21));
        comboBox_4 = new QComboBox(scrollAreaWidgetContents_2);
        comboBox_4->setObjectName(QStringLiteral("comboBox_4"));
        comboBox_4->setGeometry(QRect(122, 5, 101, 22));
        scrollArea_2->setWidget(scrollAreaWidgetContents_2);
        frame_01 = new QFrame(frame);
        frame_01->setObjectName(QStringLiteral("frame_01"));
        frame_01->setGeometry(QRect(0, 40, 241, 200));
        frame_01->setMinimumSize(QSize(241, 200));
        frame_01->setMaximumSize(QSize(241, 251));
        frame_01->setFrameShape(QFrame::StyledPanel);
        frame_01->setFrameShadow(QFrame::Raised);
        label_30 = new QLabel(frame_01);
        label_30->setObjectName(QStringLiteral("label_30"));
        label_30->setGeometry(QRect(4, 154, 121, 31));
        dial_rotatevar = new QDial(frame_01);
        dial_rotatevar->setObjectName(QStringLiteral("dial_rotatevar"));
        dial_rotatevar->setGeometry(QRect(110, 155, 41, 31));
        dial_rotatevar->setMaximum(360);
        dial_minr = new QDial(frame_01);
        dial_minr->setObjectName(QStringLiteral("dial_minr"));
        dial_minr->setGeometry(QRect(110, 75, 41, 31));
        dial_minr->setMaximum(360);
        label_32 = new QLabel(frame_01);
        label_32->setObjectName(QStringLiteral("label_32"));
        label_32->setGeometry(QRect(4, 2, 91, 21));
        dial_maxr = new QDial(frame_01);
        dial_maxr->setObjectName(QStringLiteral("dial_maxr"));
        dial_maxr->setGeometry(QRect(110, -4, 41, 31));
        dial_maxr->setMaximum(360);
        doubleSpinBox_maxr = new QDoubleSpinBox(frame_01);
        doubleSpinBox_maxr->setObjectName(QStringLiteral("doubleSpinBox_maxr"));
        doubleSpinBox_maxr->setGeometry(QRect(150, 2, 80, 22));
        doubleSpinBox_maxr->setMaximum(360);
        doubleSpinBox_maxr->setSingleStep(3);
        doubleSpinBox_minr = new QDoubleSpinBox(frame_01);
        doubleSpinBox_minr->setObjectName(QStringLiteral("doubleSpinBox_minr"));
        doubleSpinBox_minr->setGeometry(QRect(150, 80, 80, 22));
        doubleSpinBox_minr->setMaximum(360);
        doubleSpinBox_minr->setSingleStep(3);
        line_27 = new QFrame(frame_01);
        line_27->setObjectName(QStringLiteral("line_27"));
        line_27->setEnabled(true);
        line_27->setGeometry(QRect(0, 180, 241, 16));
        line_27->setFrameShadow(QFrame::Sunken);
        line_27->setLineWidth(1);
        line_27->setFrameShape(QFrame::HLine);
        label_33 = new QLabel(frame_01);
        label_33->setObjectName(QStringLiteral("label_33"));
        label_33->setGeometry(QRect(4, 114, 91, 31));
        doubleSpinBox_maxrv = new QDoubleSpinBox(frame_01);
        doubleSpinBox_maxrv->setObjectName(QStringLiteral("doubleSpinBox_maxrv"));
        doubleSpinBox_maxrv->setGeometry(QRect(150, 38, 80, 22));
        doubleSpinBox_maxrv->setMaximum(360);
        doubleSpinBox_maxrv->setSingleStep(3);
        doubleSpinBox_rotate = new QDoubleSpinBox(frame_01);
        doubleSpinBox_rotate->setObjectName(QStringLiteral("doubleSpinBox_rotate"));
        doubleSpinBox_rotate->setGeometry(QRect(150, 120, 80, 22));
        doubleSpinBox_rotate->setMaximum(360);
        doubleSpinBox_rotate->setSingleStep(3);
        label_34 = new QLabel(frame_01);
        label_34->setObjectName(QStringLiteral("label_34"));
        label_34->setGeometry(QRect(4, 32, 91, 31));
        doubleSpinBox_rotatevar = new QDoubleSpinBox(frame_01);
        doubleSpinBox_rotatevar->setObjectName(QStringLiteral("doubleSpinBox_rotatevar"));
        doubleSpinBox_rotatevar->setGeometry(QRect(150, 160, 80, 22));
        doubleSpinBox_rotatevar->setMaximum(360);
        doubleSpinBox_rotatevar->setSingleStep(3);
        dial_maxrv = new QDial(frame_01);
        dial_maxrv->setObjectName(QStringLiteral("dial_maxrv"));
        dial_maxrv->setGeometry(QRect(110, 33, 41, 31));
        dial_maxrv->setMaximum(360);
        dial_rotate = new QDial(frame_01);
        dial_rotate->setObjectName(QStringLiteral("dial_rotate"));
        dial_rotate->setGeometry(QRect(110, 115, 41, 31));
        dial_rotate->setMaximum(360);
        label_35 = new QLabel(frame_01);
        label_35->setObjectName(QStringLiteral("label_35"));
        label_35->setGeometry(QRect(4, 74, 91, 31));
        line_28 = new QFrame(frame_01);
        line_28->setObjectName(QStringLiteral("line_28"));
        line_28->setEnabled(true);
        line_28->setGeometry(QRect(0, 100, 241, 16));
        line_28->setFrameShadow(QFrame::Sunken);
        line_28->setLineWidth(1);
        line_28->setFrameShape(QFrame::HLine);
        line_29 = new QFrame(frame_01);
        line_29->setObjectName(QStringLiteral("line_29"));
        line_29->setEnabled(true);
        line_29->setGeometry(QRect(0, 58, 241, 16));
        line_29->setFrameShadow(QFrame::Sunken);
        line_29->setLineWidth(1);
        line_29->setFrameShape(QFrame::HLine);
        line_30 = new QFrame(frame_01);
        line_30->setObjectName(QStringLiteral("line_30"));
        line_30->setEnabled(true);
        line_30->setGeometry(QRect(0, 20, 241, 16));
        line_30->setFrameShadow(QFrame::Sunken);
        line_30->setLineWidth(1);
        line_30->setFrameShape(QFrame::HLine);
        line_31 = new QFrame(frame_01);
        line_31->setObjectName(QStringLiteral("line_31"));
        line_31->setEnabled(true);
        line_31->setGeometry(QRect(0, 140, 241, 16));
        line_31->setFrameShadow(QFrame::Sunken);
        line_31->setLineWidth(1);
        line_31->setFrameShape(QFrame::HLine);
        frame_2 = new QFrame(frame);
        frame_2->setObjectName(QStringLiteral("frame_2"));
        frame_2->setGeometry(QRect(0, 40, 241, 320));
        frame_2->setMinimumSize(QSize(241, 200));
        frame_2->setMaximumSize(QSize(241, 320));
        frame_2->setFrameShape(QFrame::StyledPanel);
        frame_2->setFrameShadow(QFrame::Raised);
        label_78 = new QLabel(frame_2);
        label_78->setObjectName(QStringLiteral("label_78"));
        label_78->setGeometry(QRect(4, 129, 121, 31));
        dial_radial = new QDial(frame_2);
        dial_radial->setObjectName(QStringLiteral("dial_radial"));
        dial_radial->setGeometry(QRect(110, 131, 41, 31));
        dial_gravityx = new QDial(frame_2);
        dial_gravityx->setObjectName(QStringLiteral("dial_gravityx"));
        dial_gravityx->setGeometry(QRect(110, 64, 41, 31));
        dial_gravityx->setMinimum(-1000);
        dial_gravityx->setMaximum(1000);
        label_79 = new QLabel(frame_2);
        label_79->setObjectName(QStringLiteral("label_79"));
        label_79->setGeometry(QRect(4, 2, 91, 21));
        dial_speed = new QDial(frame_2);
        dial_speed->setObjectName(QStringLiteral("dial_speed"));
        dial_speed->setEnabled(true);
        dial_speed->setGeometry(QRect(110, -4, 41, 31));
        dial_speed->setMaximum(1000);
        doubleSpinBox_speed = new QDoubleSpinBox(frame_2);
        doubleSpinBox_speed->setObjectName(QStringLiteral("doubleSpinBox_speed"));
        doubleSpinBox_speed->setGeometry(QRect(150, 2, 80, 22));
        doubleSpinBox_speed->setMaximum(1000);
        doubleSpinBox_speed->setSingleStep(10);
        doubleSpinBox_gravityx = new QDoubleSpinBox(frame_2);
        doubleSpinBox_gravityx->setObjectName(QStringLiteral("doubleSpinBox_gravityx"));
        doubleSpinBox_gravityx->setGeometry(QRect(150, 69, 80, 22));
        doubleSpinBox_gravityx->setMinimum(-1000);
        doubleSpinBox_gravityx->setMaximum(1000);
        doubleSpinBox_gravityx->setSingleStep(20);
        line_32 = new QFrame(frame_2);
        line_32->setObjectName(QStringLiteral("line_32"));
        line_32->setEnabled(true);
        line_32->setGeometry(QRect(0, 155, 241, 16));
        line_32->setFrameShadow(QFrame::Sunken);
        line_32->setLineWidth(1);
        line_32->setFrameShape(QFrame::HLine);
        label_80 = new QLabel(frame_2);
        label_80->setObjectName(QStringLiteral("label_80"));
        label_80->setGeometry(QRect(4, 96, 91, 31));
        doubleSpinBox_speedVar = new QDoubleSpinBox(frame_2);
        doubleSpinBox_speedVar->setObjectName(QStringLiteral("doubleSpinBox_speedVar"));
        doubleSpinBox_speedVar->setGeometry(QRect(150, 35, 80, 22));
        doubleSpinBox_speedVar->setMaximum(1000);
        doubleSpinBox_speedVar->setSingleStep(10);
        doubleSpinBox_gravityy = new QDoubleSpinBox(frame_2);
        doubleSpinBox_gravityy->setObjectName(QStringLiteral("doubleSpinBox_gravityy"));
        doubleSpinBox_gravityy->setGeometry(QRect(150, 101, 80, 22));
        doubleSpinBox_gravityy->setMinimum(-1000);
        doubleSpinBox_gravityy->setMaximum(1000);
        doubleSpinBox_gravityy->setSingleStep(20);
        label_81 = new QLabel(frame_2);
        label_81->setObjectName(QStringLiteral("label_81"));
        label_81->setGeometry(QRect(4, 30, 91, 31));
        doubleSpinBox_radial = new QDoubleSpinBox(frame_2);
        doubleSpinBox_radial->setObjectName(QStringLiteral("doubleSpinBox_radial"));
        doubleSpinBox_radial->setGeometry(QRect(150, 135, 80, 22));
        doubleSpinBox_radial->setMaximum(1000);
        doubleSpinBox_radial->setSingleStep(10);
        dial_speedVar = new QDial(frame_2);
        dial_speedVar->setObjectName(QStringLiteral("dial_speedVar"));
        dial_speedVar->setGeometry(QRect(110, 30, 41, 31));
        dial_speedVar->setMaximum(1000);
        dial_gravityy = new QDial(frame_2);
        dial_gravityy->setObjectName(QStringLiteral("dial_gravityy"));
        dial_gravityy->setGeometry(QRect(110, 96, 41, 31));
        dial_gravityy->setMinimum(-1000);
        dial_gravityy->setMaximum(1000);
        label_82 = new QLabel(frame_2);
        label_82->setObjectName(QStringLiteral("label_82"));
        label_82->setGeometry(QRect(4, 63, 91, 31));
        line_33 = new QFrame(frame_2);
        line_33->setObjectName(QStringLiteral("line_33"));
        line_33->setEnabled(true);
        line_33->setGeometry(QRect(0, 88, 241, 16));
        line_33->setFrameShadow(QFrame::Sunken);
        line_33->setLineWidth(1);
        line_33->setFrameShape(QFrame::HLine);
        line_34 = new QFrame(frame_2);
        line_34->setObjectName(QStringLiteral("line_34"));
        line_34->setEnabled(true);
        line_34->setGeometry(QRect(0, 54, 241, 16));
        line_34->setFrameShadow(QFrame::Sunken);
        line_34->setLineWidth(1);
        line_34->setFrameShape(QFrame::HLine);
        line_35 = new QFrame(frame_2);
        line_35->setObjectName(QStringLiteral("line_35"));
        line_35->setEnabled(true);
        line_35->setGeometry(QRect(0, 20, 241, 16));
        line_35->setFrameShadow(QFrame::Sunken);
        line_35->setLineWidth(1);
        line_35->setFrameShape(QFrame::HLine);
        line_36 = new QFrame(frame_2);
        line_36->setObjectName(QStringLiteral("line_36"));
        line_36->setEnabled(true);
        line_36->setGeometry(QRect(0, 120, 241, 16));
        line_36->setFrameShadow(QFrame::Sunken);
        line_36->setLineWidth(1);
        line_36->setFrameShape(QFrame::HLine);
        line_39 = new QFrame(frame_2);
        line_39->setObjectName(QStringLiteral("line_39"));
        line_39->setEnabled(true);
        line_39->setGeometry(QRect(0, 260, 241, 16));
        line_39->setFrameShadow(QFrame::Sunken);
        line_39->setLineWidth(1);
        line_39->setFrameShape(QFrame::HLine);
        doubleSpinBox_tangential = new QDoubleSpinBox(frame_2);
        doubleSpinBox_tangential->setObjectName(QStringLiteral("doubleSpinBox_tangential"));
        doubleSpinBox_tangential->setGeometry(QRect(150, 205, 80, 22));
        doubleSpinBox_tangential->setMaximum(1000);
        doubleSpinBox_tangential->setSingleStep(10);
        label_85 = new QLabel(frame_2);
        label_85->setObjectName(QStringLiteral("label_85"));
        label_85->setGeometry(QRect(4, 234, 121, 31));
        dial_radialvar = new QDial(frame_2);
        dial_radialvar->setObjectName(QStringLiteral("dial_radialvar"));
        dial_radialvar->setGeometry(QRect(110, 165, 41, 31));
        dial_radialvar->setMaximum(1000);
        doubleSpinBox_radialvar = new QDoubleSpinBox(frame_2);
        doubleSpinBox_radialvar->setObjectName(QStringLiteral("doubleSpinBox_radialvar"));
        doubleSpinBox_radialvar->setGeometry(QRect(150, 170, 80, 22));
        doubleSpinBox_radialvar->setMaximum(1000);
        doubleSpinBox_radialvar->setSingleStep(10);
        dial_tangential = new QDial(frame_2);
        dial_tangential->setObjectName(QStringLiteral("dial_tangential"));
        dial_tangential->setGeometry(QRect(110, 201, 41, 31));
        dial_tangential->setMaximum(1000);
        label_84 = new QLabel(frame_2);
        label_84->setObjectName(QStringLiteral("label_84"));
        label_84->setGeometry(QRect(4, 199, 121, 31));
        dial_tangvar = new QDial(frame_2);
        dial_tangvar->setObjectName(QStringLiteral("dial_tangvar"));
        dial_tangvar->setGeometry(QRect(110, 235, 41, 31));
        dial_tangvar->setMaximum(1000);
        label_83 = new QLabel(frame_2);
        label_83->setObjectName(QStringLiteral("label_83"));
        label_83->setGeometry(QRect(4, 164, 121, 31));
        line_37 = new QFrame(frame_2);
        line_37->setObjectName(QStringLiteral("line_37"));
        line_37->setEnabled(true);
        line_37->setGeometry(QRect(0, 190, 241, 16));
        line_37->setFrameShadow(QFrame::Sunken);
        line_37->setLineWidth(1);
        line_37->setFrameShape(QFrame::HLine);
        line_38 = new QFrame(frame_2);
        line_38->setObjectName(QStringLiteral("line_38"));
        line_38->setEnabled(true);
        line_38->setGeometry(QRect(0, 225, 241, 16));
        line_38->setFrameShadow(QFrame::Sunken);
        line_38->setLineWidth(1);
        line_38->setFrameShape(QFrame::HLine);
        doubleSpinBox_tangvar = new QDoubleSpinBox(frame_2);
        doubleSpinBox_tangvar->setObjectName(QStringLiteral("doubleSpinBox_tangvar"));
        doubleSpinBox_tangvar->setGeometry(QRect(150, 240, 80, 22));
        doubleSpinBox_tangvar->setMaximum(1000);
        doubleSpinBox_tangvar->setSingleStep(10);

        verticalLayout_2->addWidget(frame);

        groupBox = new QGroupBox(dockWidgetContents_5);
        groupBox->setObjectName(QStringLiteral("groupBox"));
        groupBox->setMinimumSize(QSize(241, 150));
        groupBox->setMaximumSize(QSize(241, 150));
        line_25 = new QFrame(groupBox);
        line_25->setObjectName(QStringLiteral("line_25"));
        line_25->setEnabled(true);
        line_25->setGeometry(QRect(0, 30, 241, 16));
        line_25->setFrameShadow(QFrame::Sunken);
        line_25->setLineWidth(1);
        line_25->setFrameShape(QFrame::HLine);
        doubleSpinBox_x = new QDoubleSpinBox(groupBox);
        doubleSpinBox_x->setObjectName(QStringLiteral("doubleSpinBox_x"));
        doubleSpinBox_x->setGeometry(QRect(150, 10, 80, 22));
        doubleSpinBox_x->setMinimum(-500);
        doubleSpinBox_x->setMaximum(1000);
        doubleSpinBox_x->setSingleStep(3);
        label_28 = new QLabel(groupBox);
        label_28->setObjectName(QStringLiteral("label_28"));
        label_28->setGeometry(QRect(4, 4, 121, 31));
        dial_x = new QDial(groupBox);
        dial_x->setObjectName(QStringLiteral("dial_x"));
        dial_x->setGeometry(QRect(110, 5, 41, 31));
        dial_x->setMinimum(-500);
        dial_x->setMaximum(1000);
        line_26 = new QFrame(groupBox);
        line_26->setObjectName(QStringLiteral("line_26"));
        line_26->setEnabled(true);
        line_26->setGeometry(QRect(0, 70, 241, 16));
        line_26->setFrameShadow(QFrame::Sunken);
        line_26->setLineWidth(1);
        line_26->setFrameShape(QFrame::HLine);
        label_29 = new QLabel(groupBox);
        label_29->setObjectName(QStringLiteral("label_29"));
        label_29->setGeometry(QRect(4, 44, 121, 31));
        doubleSpinBox_y = new QDoubleSpinBox(groupBox);
        doubleSpinBox_y->setObjectName(QStringLiteral("doubleSpinBox_y"));
        doubleSpinBox_y->setGeometry(QRect(150, 50, 80, 22));
        doubleSpinBox_y->setMinimum(-500);
        doubleSpinBox_y->setMaximum(1000);
        doubleSpinBox_y->setSingleStep(3);
        dial_y = new QDial(groupBox);
        dial_y->setObjectName(QStringLiteral("dial_y"));
        dial_y->setGeometry(QRect(110, 45, 41, 31));
        dial_y->setMinimum(-500);
        dial_y->setMaximum(1000);

        verticalLayout_2->addWidget(groupBox);

        dockWidget_2->setWidget(dockWidgetContents_5);
        QtApplicationClass->addDockWidget(static_cast<Qt::DockWidgetArea>(2), dockWidget_2);

        menuBar->addAction(menu_File->menuAction());
        menuBar->addAction(menu_View->menuAction());
        menuBar->addAction(menu_Example->menuAction());
        menuBar->addAction(menu_Window->menuAction());
        menuBar->addAction(menu_Help->menuAction());
        menu_File->addAction(action_Open);
        menu_File->addAction(menu_History->menuAction());
        menu_File->addSeparator();
        menu_File->addAction(actionSave);
        menu_File->addAction(actionSave_As);
        menu_File->addSeparator();
        menu_File->addAction(action_Quit);
        menu_View->addAction(action_ToolBar);
        menu_Window->addAction(actionMaximum);
        menu_Window->addAction(actionMinimum);
        menu_Window->addAction(actionFull_Screen);
        menu_Help->addAction(action_About_2);
        mainToolBar->addAction(actionOpen);
        mainToolBar->addAction(action_Save);
        mainToolBar->addAction(actionSave_as);
        mainToolBar->addAction(action_Play);
        mainToolBar->addAction(action_Reset);
        mainToolBar->addAction(action_About);

        retranslateUi(QtApplicationClass);
        QObject::connect(horizontalScrollBar, SIGNAL(valueChanged(int)), label_26, SLOT(setNum(int)));
        QObject::connect(horizontalScrollBar_2, SIGNAL(valueChanged(int)), label_27, SLOT(setNum(int)));
        QObject::connect(horizontalScrollBar_3, SIGNAL(valueChanged(int)), label_36, SLOT(setNum(int)));
        QObject::connect(horizontalScrollBar_4, SIGNAL(valueChanged(int)), label_37, SLOT(setNum(int)));
        QObject::connect(horizontalScrollBar_17, SIGNAL(valueChanged(int)), label_62, SLOT(setNum(int)));
        QObject::connect(horizontalScrollBar_18, SIGNAL(valueChanged(int)), label_63, SLOT(setNum(int)));
        QObject::connect(horizontalScrollBar_19, SIGNAL(valueChanged(int)), label_64, SLOT(setNum(int)));
        QObject::connect(horizontalScrollBar_20, SIGNAL(valueChanged(int)), label_65, SLOT(setNum(int)));
        QObject::connect(horizontalScrollBar_21, SIGNAL(valueChanged(int)), label_70, SLOT(setNum(int)));
        QObject::connect(horizontalScrollBar_22, SIGNAL(valueChanged(int)), label_71, SLOT(setNum(int)));
        QObject::connect(horizontalScrollBar_23, SIGNAL(valueChanged(int)), label_72, SLOT(setNum(int)));
        QObject::connect(horizontalScrollBar_24, SIGNAL(valueChanged(int)), label_73, SLOT(setNum(int)));
        QObject::connect(horizontalScrollBar_9, SIGNAL(valueChanged(int)), label_46, SLOT(setNum(int)));
        QObject::connect(horizontalScrollBar_10, SIGNAL(valueChanged(int)), label_47, SLOT(setNum(int)));
        QObject::connect(horizontalScrollBar_11, SIGNAL(valueChanged(int)), label_48, SLOT(setNum(int)));
        QObject::connect(horizontalScrollBar_12, SIGNAL(valueChanged(int)), label_49, SLOT(setNum(int)));
        QObject::connect(horizontalScrollBar_13, SIGNAL(valueChanged(int)), label_54, SLOT(setNum(int)));
        QObject::connect(horizontalScrollBar_14, SIGNAL(valueChanged(int)), label_55, SLOT(setNum(int)));
        QObject::connect(horizontalScrollBar_15, SIGNAL(valueChanged(int)), label_56, SLOT(setNum(int)));
        QObject::connect(horizontalScrollBar_16, SIGNAL(valueChanged(int)), label_57, SLOT(setNum(int)));

        tabWidget->setCurrentIndex(0);


        QMetaObject::connectSlotsByName(QtApplicationClass);
    } // setupUi

    void retranslateUi(QMainWindow *QtApplicationClass)
    {
        QtApplicationClass->setWindowTitle(QApplication::translate("QtApplicationClass", "Particle Editor", 0));
        actionOpen->setText(QApplication::translate("QtApplicationClass", "Open", 0));
        actionOpen->setShortcut(QApplication::translate("QtApplicationClass", "Ctrl+O", 0));
        action_Save->setText(QApplication::translate("QtApplicationClass", "&Save", 0));
        action_Open->setText(QApplication::translate("QtApplicationClass", "&Open", 0));
        actionSave_As->setText(QApplication::translate("QtApplicationClass", "Save &As", 0));
        action_Quit->setText(QApplication::translate("QtApplicationClass", "&Quit", 0));
        action_Play->setText(QApplication::translate("QtApplicationClass", "&Play", 0));
#ifndef QT_NO_TOOLTIP
        action_Play->setToolTip(QApplication::translate("QtApplicationClass", "\346\222\255\346\224\276\347\262\222\345\255\220\345\212\250\347\224\273", 0));
#endif // QT_NO_TOOLTIP
        action_Reset->setText(QApplication::translate("QtApplicationClass", "&Reset", 0));
        actionSave_as->setText(QApplication::translate("QtApplicationClass", "Save &as", 0));
        action_About->setText(QApplication::translate("QtApplicationClass", "&About", 0));
        actionSave->setText(QApplication::translate("QtApplicationClass", "&Save", 0));
        action_About_2->setText(QApplication::translate("QtApplicationClass", "&About", 0));
        action_ToolBar->setText(QApplication::translate("QtApplicationClass", "&ToolBar", 0));
        actionMaximum->setText(QApplication::translate("QtApplicationClass", "Maximum", 0));
        actionMinimum->setText(QApplication::translate("QtApplicationClass", "Minimum", 0));
        actionFull_Screen->setText(QApplication::translate("QtApplicationClass", "Full Screen", 0));
        groupBox_10->setTitle(QApplication::translate("QtApplicationClass", "Start Color", 0));
        label_62->setText(QApplication::translate("QtApplicationClass", "0", 0));
        label_63->setText(QApplication::translate("QtApplicationClass", "0", 0));
        label_64->setText(QApplication::translate("QtApplicationClass", "0", 0));
        label_65->setText(QApplication::translate("QtApplicationClass", "0", 0));
        label_66->setText(QApplication::translate("QtApplicationClass", "Red", 0));
        label_67->setText(QApplication::translate("QtApplicationClass", "Green", 0));
        label_68->setText(QApplication::translate("QtApplicationClass", "Blue", 0));
        label_69->setText(QApplication::translate("QtApplicationClass", "Alpha", 0));
        pushButton_3->setText(QString());
        groupBox_11->setTitle(QApplication::translate("QtApplicationClass", "Start Color Var", 0));
        label_70->setText(QApplication::translate("QtApplicationClass", "0", 0));
        label_71->setText(QApplication::translate("QtApplicationClass", "0", 0));
        label_72->setText(QApplication::translate("QtApplicationClass", "0", 0));
        label_73->setText(QApplication::translate("QtApplicationClass", "0", 0));
        label_74->setText(QApplication::translate("QtApplicationClass", "Red", 0));
        label_75->setText(QApplication::translate("QtApplicationClass", "Green", 0));
        label_76->setText(QApplication::translate("QtApplicationClass", "Blue", 0));
        label_77->setText(QApplication::translate("QtApplicationClass", "Alpha", 0));
        pushButton_4->setText(QString());
        tabWidget->setTabText(tabWidget->indexOf(tab), QApplication::translate("QtApplicationClass", "Start Color", 0));
        groupBox_8->setTitle(QApplication::translate("QtApplicationClass", "End Color", 0));
        label_46->setText(QApplication::translate("QtApplicationClass", "0", 0));
        label_47->setText(QApplication::translate("QtApplicationClass", "0", 0));
        label_48->setText(QApplication::translate("QtApplicationClass", "0", 0));
        label_49->setText(QApplication::translate("QtApplicationClass", "0", 0));
        label_50->setText(QApplication::translate("QtApplicationClass", "Red", 0));
        label_51->setText(QApplication::translate("QtApplicationClass", "Green", 0));
        label_52->setText(QApplication::translate("QtApplicationClass", "Blue", 0));
        label_53->setText(QApplication::translate("QtApplicationClass", "Alpha", 0));
        pushButton_5->setText(QString());
        groupBox_9->setTitle(QApplication::translate("QtApplicationClass", "End Color Var", 0));
        label_54->setText(QApplication::translate("QtApplicationClass", "0", 0));
        label_55->setText(QApplication::translate("QtApplicationClass", "0", 0));
        label_56->setText(QApplication::translate("QtApplicationClass", "0", 0));
        label_57->setText(QApplication::translate("QtApplicationClass", "0", 0));
        label_58->setText(QApplication::translate("QtApplicationClass", "Red", 0));
        label_59->setText(QApplication::translate("QtApplicationClass", "Green", 0));
        label_60->setText(QApplication::translate("QtApplicationClass", "Blue", 0));
        label_61->setText(QApplication::translate("QtApplicationClass", "Alpha", 0));
        pushButton_6->setText(QString());
        tabWidget->setTabText(tabWidget->indexOf(tab_2), QApplication::translate("QtApplicationClass", "End Color", 0));
        groupBox_6->setTitle(QApplication::translate("QtApplicationClass", "Background Color", 0));
        label_26->setText(QApplication::translate("QtApplicationClass", "0", 0));
        label_27->setText(QApplication::translate("QtApplicationClass", "0", 0));
        label_36->setText(QApplication::translate("QtApplicationClass", "0", 0));
        label_37->setText(QApplication::translate("QtApplicationClass", "0", 0));
        label_22->setText(QApplication::translate("QtApplicationClass", "Red", 0));
        label_23->setText(QApplication::translate("QtApplicationClass", "Green", 0));
        label_24->setText(QApplication::translate("QtApplicationClass", "Blue", 0));
        label_25->setText(QApplication::translate("QtApplicationClass", "Alpha", 0));
        pushButton_7->setText(QString());
        groupBox_7->setTitle(QApplication::translate("QtApplicationClass", "Background Image", 0));
        label_87->setText(QString());
        pushButton->setText(QApplication::translate("QtApplicationClass", "Choose File", 0));
        checkBox->setText(QApplication::translate("QtApplicationClass", "Show/Hide", 0));
        checkBox_2->setText(QApplication::translate("QtApplicationClass", "Moved", 0));
        tabWidget->setTabText(tabWidget->indexOf(tab_3), QApplication::translate("QtApplicationClass", "Background", 0));
        menu_File->setTitle(QApplication::translate("QtApplicationClass", "&File", 0));
        menu_History->setTitle(QApplication::translate("QtApplicationClass", "&History", 0));
        menu_View->setTitle(QApplication::translate("QtApplicationClass", "&View", 0));
        menu_Window->setTitle(QApplication::translate("QtApplicationClass", "&Window", 0));
        menu_Example->setTitle(QApplication::translate("QtApplicationClass", "&Example", 0));
        menu_Help->setTitle(QApplication::translate("QtApplicationClass", "&Help", 0));
        mainToolBar->setWindowTitle(QApplication::translate("QtApplicationClass", "ToolBar", 0));
#ifndef QT_NO_TOOLTIP
        Properties->setToolTip(QString());
#endif // QT_NO_TOOLTIP
        Properties->setWindowTitle(QApplication::translate("QtApplicationClass", "Particle Properties", 0));
        label->setText(QApplication::translate("QtApplicationClass", "Duration", 0));
        label_2->setText(QApplication::translate("QtApplicationClass", "Max Particles", 0));
        label_3->setText(QApplication::translate("QtApplicationClass", "Particle \n"
"Lifespan", 0));
        label_4->setText(QApplication::translate("QtApplicationClass", "Lifespan\n"
"Variance", 0));
        label_5->setText(QApplication::translate("QtApplicationClass", "Start Size", 0));
        label_6->setText(QApplication::translate("QtApplicationClass", "Start Size Var", 0));
        label_7->setText(QApplication::translate("QtApplicationClass", "Finish Size", 0));
        label_8->setText(QApplication::translate("QtApplicationClass", "Finish Size Var", 0));
        label_14->setText(QApplication::translate("QtApplicationClass", "Angle", 0));
        label_15->setText(QApplication::translate("QtApplicationClass", "Angle Var", 0));
        label_16->setText(QApplication::translate("QtApplicationClass", "Rotation Start", 0));
        label_17->setText(QApplication::translate("QtApplicationClass", "Rotation Start\n"
"Variance", 0));
        label_18->setText(QApplication::translate("QtApplicationClass", "Rotation End", 0));
        label_19->setText(QApplication::translate("QtApplicationClass", "Rotation End\n"
"Variance", 0));
        Blend->setWindowTitle(QApplication::translate("QtApplicationClass", "Blend Function", 0));
        label_20->setText(QApplication::translate("QtApplicationClass", "Src", 0));
        comboBox->clear();
        comboBox->insertItems(0, QStringList()
         << QApplication::translate("QtApplicationClass", "GL_ZERO", 0)
         << QApplication::translate("QtApplicationClass", "GL_ONE", 0)
         << QApplication::translate("QtApplicationClass", "GL_SRC_COLOR", 0)
         << QApplication::translate("QtApplicationClass", "GL_ONE_MINUS_SRC_COLOR", 0)
         << QApplication::translate("QtApplicationClass", "GL_SRC_ALPHA", 0)
         << QApplication::translate("QtApplicationClass", "GL_ONE_MINUS_SRC_ALPHA", 0)
         << QApplication::translate("QtApplicationClass", "GL_DST_COLOR", 0)
         << QApplication::translate("QtApplicationClass", "GL_ONE_MINUS_DST_COLOR", 0)
         << QApplication::translate("QtApplicationClass", "GL_DST_ALPHA", 0)
         << QApplication::translate("QtApplicationClass", "GL_ONE_MINUS_DST_ALPHA", 0)
         << QApplication::translate("QtApplicationClass", "GL_SRC_ALPHA_SATURATE", 0)
        );
        btn_normal->setText(QApplication::translate("QtApplicationClass", "Normal", 0));
        label_21->setText(QApplication::translate("QtApplicationClass", "Dst", 0));
        pushButton_2->setText(QApplication::translate("QtApplicationClass", "Additive", 0));
        comboBox_2->clear();
        comboBox_2->insertItems(0, QStringList()
         << QApplication::translate("QtApplicationClass", "GL_ZERO", 0)
         << QApplication::translate("QtApplicationClass", "GL_ONE", 0)
         << QApplication::translate("QtApplicationClass", "GL_SRC_COLOR", 0)
         << QApplication::translate("QtApplicationClass", "GL_ONE_MINUS_SRC_COLOR", 0)
         << QApplication::translate("QtApplicationClass", "GL_SRC_ALPHA", 0)
         << QApplication::translate("QtApplicationClass", "GL_ONE_MINUS_SRC_ALPHA", 0)
         << QApplication::translate("QtApplicationClass", "GL_DST_COLOR", 0)
         << QApplication::translate("QtApplicationClass", "GL_ONE_MINUS_DST_COLOR", 0)
         << QApplication::translate("QtApplicationClass", "GL_DST_ALPHA", 0)
         << QApplication::translate("QtApplicationClass", "GL_ONE_MINUS_DST_ALPHA", 0)
         << QApplication::translate("QtApplicationClass", "GL_SRC_ALPHA_SATURATE", 0)
        );
        dockWidget->setWindowTitle(QApplication::translate("QtApplicationClass", "Particle Texture", 0));
        label_86->setText(QString());
        choose_texture->setText(QApplication::translate("QtApplicationClass", "Choose", 0));
        dockWidget_2->setWindowTitle(QApplication::translate("QtApplicationClass", "Particle Emitter Properties", 0));
        label_31->setText(QApplication::translate("QtApplicationClass", "Emitter Type", 0));
        comboBox_4->clear();
        comboBox_4->insertItems(0, QStringList()
         << QApplication::translate("QtApplicationClass", "Gravity", 0)
         << QApplication::translate("QtApplicationClass", "Radial", 0)
        );
        label_30->setText(QApplication::translate("QtApplicationClass", "Rotate\n"
"PerSecondVariance", 0));
        label_32->setText(QApplication::translate("QtApplicationClass", "Max Radius", 0));
        label_33->setText(QApplication::translate("QtApplicationClass", "Rotate Per\n"
"Second", 0));
        label_34->setText(QApplication::translate("QtApplicationClass", "Max Radius\n"
"Variance", 0));
        label_35->setText(QApplication::translate("QtApplicationClass", "Min Radius", 0));
        label_78->setText(QApplication::translate("QtApplicationClass", "Radial\n"
"Acceleration", 0));
        label_79->setText(QApplication::translate("QtApplicationClass", "Speed", 0));
        label_80->setText(QApplication::translate("QtApplicationClass", "Gravity y", 0));
        label_81->setText(QApplication::translate("QtApplicationClass", "Speed Variance", 0));
        label_82->setText(QApplication::translate("QtApplicationClass", "Gravity x", 0));
        label_85->setText(QApplication::translate("QtApplicationClass", "Tangential Accel\n"
"Variance", 0));
        label_84->setText(QApplication::translate("QtApplicationClass", "Tangential\n"
"Acceleration", 0));
        label_83->setText(QApplication::translate("QtApplicationClass", "Radial Accel\n"
"Variance", 0));
        groupBox->setTitle(QString());
        label_28->setText(QApplication::translate("QtApplicationClass", "Variance X", 0));
        label_29->setText(QApplication::translate("QtApplicationClass", "Variance Y", 0));
    } // retranslateUi

};

namespace Ui {
    class QtApplicationClass: public Ui_QtApplicationClass {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_QTAPPLICATION_H
